name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: pettrack.azurecr.io
  IMAGE_NAME: veterinary-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push auth-service
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:latest ./services/auth-service
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:latest
    
    - name: Build and push web-client
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:latest ./clients/web-client
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:latest

    - name: Build and push appointment-service
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointment-service:latest ./services/appointment-service
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointment-service:latest
    
    - name: Deploy to Azure App Service
      if: github.ref == 'refs/heads/dev'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'veterinary-app'
        slot-name: 'production'
        images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointment-service:latest'