name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]  

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  TAG: latest
  APP_NAME: veterinary-app
  SLOT_NAME: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push auth-service
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME-auth-service:$TAG ./services/auth-service
        docker push $REGISTRY/$IMAGE_NAME-auth-service:$TAG
    
    - name: Build and push web-client
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME-web-client:$TAG ./clients/web-client
        docker push $REGISTRY/$IMAGE_NAME-web-client:$TAG

    - name: Build and push appointment-service
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME-appointment-service:$TAG ./services/appointment-service
        docker push $REGISTRY/$IMAGE_NAME-appointment-service:$TAG
    
    - name: Build and push api-gateway
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME-api-gateway:$TAG ./services/api-gateway
        docker push $REGISTRY/$IMAGE_NAME-api-gateway:$TAG    
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: ${{ env.SLOT_NAME }}
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth-service:${{ env.TAG }},
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web-client:${{ env.TAG }},
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-appointment-service:${{ env.TAG }},
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api-gateway:${{ env.TAG }}
